import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../globals.css";
import MainFooter from "@/components/main-footer/MainFooter";
import Providers from "../providers";
import MainHeader from "@/components/main-header/MainHeader";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable}`}>
        <Providers>
          <MainHeader />
          {children}
          <MainFooter />
        </Providers>
      </body>
    </html>
  );
}
