import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-header/MainHeader";
import MainFooter from "@/components/main-footer/MainFooter";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} `}>
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
